# @package _global_

defaults:
  - default

ckpt_path: /opt/hpcaas/.mounts/fs-0565f60d669b6a2d3/home/jianingy/research/accel-cortex/dust3r/fast3r/logs/fp32_bs2_views8/runs/fp32_bs2_views8_3782638/checkpoints/last.ckpt

