# @package _global_

defaults:
  - default

ckpt_path: /opt/hpcaas/.mounts/fs-0565f60d669b6a2d3/home/jianingy/research/accel-cortex/dust3r/fast3r/logs/train/runs/2024-08-13_08-06-08/checkpoints/last.ckpt

