# @package _global_

defaults:
  - default

# ckpt_path: /opt/hpcaas/.mounts/fs-0565f60d669b6a2d3/home/jianingy/research/accel-cortex/dust3r/fast3r/logs/fast3r_habitat_larger_decoder_views4/runs/fast3r_habitat_larger_decoder_views4_4383740/checkpoints/last.ckpt
# ckpt_path: /opt/hpcaas/.mounts/fs-0565f60d669b6a2d3/home/jianingy/research/accel-cortex/dust3r/fast3r/logs/fast3r_co3d_scannetpp_arkitscenes_better_random_pose_emb/runs/fast3r_co3d_scannetpp_arkitscenes_better_random_pose_emb_4365927/checkpoints/last.ckpt
# ckpt_path: /opt/hpcaas/.mounts/fs-0565f60d669b6a2d3/home/jianingy/research/accel-cortex/dust3r/fast3r/logs/fast3r_larger_decoder_bs1_views4/runs/fast3r_larger_decoder_4371625/checkpoints/last.ckpt
# ckpt_path: /opt/hpcaas/.mounts/fs-0565f60d669b6a2d3/home/jianingy/research/accel-cortex/dust3r/fast3r/logs/fast3r_co3d_only_views8/runs/fast3r_co3d_only_views8_4439657/checkpoints/last.ckpt
# ckpt_path: /opt/hpcaas/.mounts/fs-0565f60d669b6a2d3/home/jianingy/research/accel-cortex/dust3r/fast3r/logs/fast3r_no_local_head/runs/fast3r_no_local_head_4611636/checkpoints/last.ckpt
ckpt_path: /opt/hpcaas/.mounts/fs-0565f60d669b6a2d3/home/jianingy/research/accel-cortex/dust3r/fast3r/logs/fast3r_no_local_head_habitat/runs/fast3r_no_local_head_habitat_4615832/checkpoints/last.ckpt
# ckpt_path: /opt/hpcaas/.mounts/fs-0565f60d669b6a2d3/home/jianingy/research/accel-cortex/dust3r/fast3r/logs/fast3r_local_head/runs/fast3r_local_head_4638120/checkpoints/last.ckpt
# ckpt_path: /opt/hpcaas/.mounts/fs-0565f60d669b6a2d3/home/jianingy/research/accel-cortex/dust3r/fast3r/logs/fast3r_local_head_habitat/runs/fast3r_local_head_habitat_4626119/checkpoints/last.ckpt

data:
  num_views_val: 10
  data_module:
    validation_datasets:
      # - DTU(split='test', ROOT='${data.data_root}/dtu_test_mvsnet_release', resolution=512, num_seq=1, full_video=True, kf_every=15)
      - 8 @ NRGBD(split='test', ROOT='${data.data_root}/neural_rgbd', resolution=512, num_seq=1, num_frames=${data.num_views_val}, full_video=False)
      - 8 @ SevenScenes(split='test', ROOT='${data.data_root}/7_scenes_processed', resolution=512, num_seq=1, num_frames=${data.num_views_val}, full_video=False)
      - 100 @ Habitat_Multiview(100_000, split='val', num_views=${data.num_views_val}, ROOT='${data.data_root}/habitat_processed', resolution=(512,384), seed=777)
    num_workers: 0 # debuggers don't like multiprocessing
    pin_memory: false # disable gpu memory pin
    batch_size_per_device: 6
    batch_size_per_device_val: 4
