# @package _global_

defaults:
  - _self_
  - data: multiview_dust3r
  - model: multiview_dust3r
  - logger: null
  - trainer: ddp
  - paths: default
  - extras: default
  - hydra: default
  - eval: default

task_name: "eval"

tags: ["dev"]

# passing checkpoint path is necessary for evaluation
ckpt_path: ???
